// Fill out your copyright notice in the Description page of Project Settings.


#include "PlayerCharacter.h"

#include "Camera/CameraComponent.h"
#include "GameFramework/SpringArmComponent.h"
#include "InputMappingContext.h"
#include "Interactable.h" 
#include "EnhancedInputComponent.h"
#include "EnhancedInputSubsystems.h"
#include "MyCharacterMovementComponent.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "Components/BoxComponent.h"
#include "Components/CapsuleComponent.h"
#include "Materials/MaterialParameterCollectionInstance.h"

APlayerCharacter::APlayerCharacter(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer.SetDefaultSubobjectClass<UMyCharacterMovementComponent>(ACharacter::CharacterMovementComponentName))
{
	PrimaryActorTick.bCanEverTick = true;
	this->bUseControllerRotationYaw = false;

	// ì¹´ë©”ë¼ ì„¤ì •
	this->CameraBoom = CreateDefaultSubobject<USpringArmComponent>(TEXT("CameraBoom"));
	this->CameraBoom->SetupAttachment(this->GetRootComponent());
	this->CameraBoom->TargetArmLength = 4000.f;
	this->CameraBoom->bUsePawnControlRotation = false;
	this->CameraBoom->SetRelativeRotation(FRotator(0.f, 0.f, 0.f));
	// ì¶©ëŒ ì‹œ ì¹´ë©”ë¼ ê±°ë¦¬ ì¤„ì–´ë“œëŠ” ë¬¸ì œ ë°©ì§€
	CameraBoom->bDoCollisionTest = false;

	this->SideViewCamera = CreateDefaultSubobject<UCameraComponent>(TEXT("SideViewCamera"));
	this->SideViewCamera->SetupAttachment(CameraBoom, USpringArmComponent::SocketName);
	this->SideViewCamera->bUsePawnControlRotation = false;

	// ì…ë ¥ ë§¤í•‘
	static ConstructorHelpers::FObjectFinder<UInputMappingContext> tempIMC(TEXT("/Script/EnhancedInput.InputMappingContext'/Game/Inputs/IMC_PlayerControls.IMC_PlayerControls'"));
	if (tempIMC.Succeeded()) {
		this->IMC_FARPlayer = tempIMC.Object;
	}

	// ìƒí˜¸ì‘ìš© ë°•ìŠ¤
	this->InteractionTrigger = CreateDefaultSubobject<UBoxComponent>(TEXT("InteractionTrigger"));
	this->InteractionTrigger->SetupAttachment(this->GetRootComponent());
	this->InteractionTrigger->SetBoxExtent(FVector(50.f, 50.f, 50.f));
	this->InteractionTrigger->SetCollisionProfileName(TEXT("Trigger"));

	// ì¶©ëŒ ì‘ë‹µ ì„¤ì •
	this->GetCapsuleComponent()->SetCollisionResponseToChannel(ECC_WorldStatic, ECR_Block);
	this->GetCapsuleComponent()->SetCollisionResponseToChannel(ECC_WorldDynamic, ECR_Block);
	this->InteractionTrigger->SetCollisionResponseToAllChannels(ECR_Ignore);
	this->InteractionTrigger->SetCollisionResponseToChannel(ECC_GameTraceChannel1, ECR_Overlap);

	// ìƒí˜¸ì‘ìš© ëŒ€ìƒ ì´ˆê¸°í™”
	this->FocusedActor = nullptr;
}


// Called when the game starts or when spawned
void APlayerCharacter::BeginPlay()
{
	Super::BeginPlay();

	// íŠ¸ë¦¬ê±° ì˜¤ë²„ë© ì´ë²¤íŠ¸ì— í•¨ìˆ˜ ë°”ì¸ë”©
	InteractionTrigger->OnComponentBeginOverlap.AddDynamic(this, &APlayerCharacter::OnInteractionTriggerBeginOverlap);
	InteractionTrigger->OnComponentEndOverlap.AddDynamic(this, &APlayerCharacter::OnInteractionTriggerEndOverlap);

	// âœ… ê³µì¤‘ ì œì–´ ê°€ëŠ¥í•˜ê²Œ ì„¤ì •
	GetCharacterMovement()->AirControl = 0.8f;

	SetSeeThroughEffect();

}

// Called every frame
void APlayerCharacter::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	if (bIsClimbingOffLadderTop)
	{
		// 1ë‹¨ê³„: Z ìœ„ì¹˜ ì˜¬ë¦¬ê¸°
		FVector CurrentLocation = GetActorLocation();
		float TargetZ = CurrentLadder->TopZ + GetCapsuleComponent()->GetScaledCapsuleHalfHeight();
		FVector TargetLocation = FVector(CurrentLocation.X, CurrentLocation.Y, TargetZ);

		SetActorLocation(FMath::VInterpTo(CurrentLocation, TargetLocation, DeltaTime, 5.f));

		if (FMath::Abs(CurrentLocation.Z - TargetZ) < 2.f)
		{
			// 2ë‹¨ê³„: ì•ìœ¼ë¡œ ì „ì§„í•  ìœ„ì¹˜ ì„¤ì • (íš¡ìŠ¤í¬ë¡¤ ê¸°ì¤€ Y ë°©í–¥)
			float ForwardOffset = 100.f;
			float DirectionSign = FMath::Sign(GetActorScale3D().Y); // ì˜¤ë¥¸ìª½ -1, ì™¼ìª½ +1
			LadderTopExitTargetLocation = FVector(CurrentLocation.X, CurrentLocation.Y + DirectionSign * ForwardOffset, TargetZ);
		
			bIsClimbingOffLadderTop = false;
			bIsExitingLadderTopForward = true;
		}
	}
	else if (bIsExitingLadderTopForward)
	{
		// ì•ìœ¼ë¡œ ì „ì§„
		FVector CurrentLocation = GetActorLocation();
		SetActorLocation(FMath::VInterpTo(CurrentLocation, LadderTopExitTargetLocation, DeltaTime, 5.f));

		if (FVector::DistSquared(CurrentLocation, LadderTopExitTargetLocation) < 4.f)
		{
			bIsExitingLadderTopForward = false;
			ExitLadderMode();
		}
	}

	
	if (bIsOnLadder && GetCharacterMovement()->IsFalling())
	{
		// ì‚¬ë‹¤ë¦¬ì—ì„œë§Œ ì¢Œìš° ì´ë™ ë§‰ê¸°
		FVector Velocity = GetCharacterMovement()->Velocity;
		if (!GetCharacterMovement()->CurrentFloor.bBlockingHit)
		{
			Velocity.Y = 0.0f;
			GetCharacterMovement()->Velocity = Velocity;
		}
	}
}

// Called to bind functionality to input
void APlayerCharacter::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);
	
	if (auto* input = Cast<UEnhancedInputComponent>(PlayerInputComponent))
	{
		input->BindAction(IA_FARMoveRight, ETriggerEvent::Triggered, this, &APlayerCharacter::OnActionMoveRight);
		input->BindAction(IA_FARJump, ETriggerEvent::Started, this, &APlayerCharacter::OnActionJump);
		input->BindAction(IA_FARJump, ETriggerEvent::Completed, this, &ACharacter::StopJumping);
		input->BindAction(IA_FARInteract, ETriggerEvent::Started, this, &APlayerCharacter::OnActionInteract);
		input->BindAction(IA_FARMoveUpDown, ETriggerEvent::Triggered, this, &APlayerCharacter::OnActionMoveUpDown);

	}

}

void APlayerCharacter::NotifyControllerChanged()
{
	Super::NotifyControllerChanged();

	// í˜„ì¬ ì»¨íŠ¸ë¡¤ëŸ¬ê°€ í”Œë ˆì´ì–´ ì»¨íŠ¸ë¡¤ëŸ¬ì¸ì§€ ê²€ì¦í•˜ê³  ì‹¶ë‹¤.
	// ë§Œì•½ ë§ë‹¤ë©´ 
	if(auto* pc = Cast<APlayerController>(Controller))
	{
		// UEnhancedInputLocalPlayerSubsystemë¥¼ ê°€ì ¸ì™€ì„œ
		auto* subsystem = ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>
		(pc->GetLocalPlayer());

		// AddMappingContextë¥¼ í•˜ê³ ì‹¶ë‹¤.
		subsystem->AddMappingContext(IMC_FARPlayer,0);
	}
}


void APlayerCharacter::OnActionMoveRight(const FInputActionValue& value)
{
	if (bIsOnLadder) return; // ì‚¬ë‹¤ë¦¬ íƒ€ëŠ” ì¤‘ì—” ì¢Œìš° ì´ë™ ë§‰ê¸°
	
	float Direction = value.Get<float>();
	AddMovementInput(FVector(0, 1, 0), Direction);

	// âœ… ë°©í–¥ì— ë”°ë¼ ìºë¦­í„° ìŠ¤ì¼€ì¼ ë°˜ì „ (íš¡ìŠ¤í¬ë¡¤ ê¸°ì¤€)
	if (!FMath::IsNearlyZero(Direction))
	{
		// ë©”ì‹œë§Œ íšŒì „: Yaw 0 (ì˜¤ë¥¸ìª½), 180 (ì™¼ìª½)
		FRotator NewMeshRotation = Direction > 0 ? FRotator(0, 0, 0) : FRotator(0, 180, 0);
		GetMesh()->SetRelativeRotation(NewMeshRotation);
	}

}

/*
void APlayerCharacter::OnActionInteract(const FInputActionValue& value)
{
	UE_LOG(LogTemp, Warning, TEXT("1 check")); 
	if (FocusedActor && FocusedActor->Implements<UInteractable>())
	{
		// í˜„ì¬ ìƒí˜¸ì‘ìš© ê°€ëŠ¥í•œ ì˜¤ë¸Œì íŠ¸ì— Interact í˜¸ì¶œ
		IInteractable::Execute_Interact(FocusedActor, this);

		UE_LOG(LogTemp, Warning, TEXT("2 check"));

	}
}*/

/*void APlayerCharacter::OnActionJump(const FInputActionValue& Value)
{
	if (bIsOnLadder)
	{
		ExitLadderMode();

		// ì¹´ë©”ë¼ ê¸°ì¤€ ì™¼ìª½ ë°©í–¥
		const float DirectionSign = -FMath::Sign(GetActorScale3D().Y); // íš¡ìŠ¤í¬ë¡¤ ê¸°ì¤€ ì¢Œìš° íŒë‹¨

		// íŠ•ê²¨ë‚˜ê°€ëŠ” í˜ ì„¤ì •
		FVector JumpOffVector = FVector(0.f, DirectionSign * 800.f, 600.f);

		LaunchCharacter(JumpOffVector, true, true);

		UE_LOG(LogTemp, Warning, TEXT("â¬†ï¸ ì‚¬ë‹¤ë¦¬ ì í”„ (%sìª½)"), DirectionSign > 0 ? TEXT("ì˜¤ë¥¸ìª½") : TEXT("ì™¼ìª½"));
		UE_LOG(LogTemp, Warning, TEXT("MovementMode After ExitLadderMode: %s"),
			*UEnum::GetValueAsString(GetCharacterMovement()->MovementMode));
	}
	else
	{
		// í˜„ì¬ ì´ë™ ì…ë ¥ ê°’ì„ ê°€ì ¸ì˜´
		float MoveDirection = 0.f;
		if (const UEnhancedInputComponent* EnhancedInput = Cast<UEnhancedInputComponent>(InputComponent))
		{
			MoveDirection = EnhancedInput->GetAxisValue(IA_FARMoveRight);
		}


		// ìˆ˜í‰ ì†ë„ ì„¤ì •
		float HorizontalSpeed = MoveDirection * GetCharacterMovement()->MaxWalkSpeed;

		// ì í”„ ì†ë„ ì„¤ì •
		float VerticalSpeed = GetCharacterMovement()->JumpZVelocity;

		// ìˆ˜í‰ ë° ìˆ˜ì§ ì†ë„ë¥¼ ë™ì‹œì— ë¶€ì—¬
		FVector LaunchVelocity = FVector(0.f, HorizontalSpeed, VerticalSpeed);
		LaunchCharacter(LaunchVelocity, true, true);

		UE_LOG(LogTemp, Warning, TEXT("â¬†ï¸ ì¼ë°˜ ì í”„ ìˆ˜í–‰"));
		UE_LOG(LogTemp, Warning, TEXT("MovementMode: %s"), *UEnum::GetValueAsString(GetCharacterMovement()->MovementMode));
	}
}*/

void APlayerCharacter::OnActionJump(const FInputActionValue& Value)
{
	if (bIsOnLadder)
	{
		// ì‚¬ë‹¤ë¦¬ ëª¨ë“œ ì¢…ë£Œ
		ExitLadderMode();

		// ì¢Œìš° ë°©í–¥ íŒë‹¨ (íš¡ìŠ¤í¬ë¡¤ ê¸°ì¤€)
		float DirectionSign = -FMath::Sign(GetActorScale3D().Y);  // ì˜¤ë¥¸ìª½ â†’ -1, ì™¼ìª½ â†’ +1

		// íŠ•ê²¨ë‚˜ê°ˆ ì†ë„ ì„¤ì •
		FVector JumpOffVelocity = FVector(0.f, DirectionSign * 600.f, 500.f);
		LaunchCharacter(JumpOffVelocity, true, true);

		UE_LOG(LogTemp, Warning, TEXT("â†©ï¸ ì‚¬ë‹¤ë¦¬ì—ì„œ íŠ•ê²¨ ì í”„ (%s ë°©í–¥)"), DirectionSign > 0 ? TEXT("ì™¼ìª½") : TEXT("ì˜¤ë¥¸ìª½"));
	}
	else
	{
		Jump(); // ê¸°ë³¸ ì í”„ë§Œ ì‚¬ìš©, í¬ë¬¼ì„  ì´ë™ì„ ìœ„í•´
		UE_LOG(LogTemp, Warning, TEXT("â¬†ï¸ ì¼ë°˜ ì í”„ ìˆ˜í–‰ (í¬ë¬¼ì„  ì ê²€ìš©)"));
	}
}


void APlayerCharacter::OnActionInteract(const FInputActionValue& value)
{
	UE_LOG(LogTemp, Warning, TEXT("âœ… Eí‚¤ ì…ë ¥ ë°œìƒ: OnActionInteract() ì§„ì…"));

	if (FocusedActor)
	{
		UE_LOG(LogTemp, Warning, TEXT("âœ… FocusedActor ì¡´ì¬: %s"), *FocusedActor->GetName());
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("âš ï¸ FocusedActor ì—†ìŒ"));
	}
	if (FocusedActor && FocusedActor->Implements<UInteractable>())
	{
		UE_LOG(LogTemp, Warning, TEXT("âœ… FocusedActorëŠ” ìƒí˜¸ì‘ìš© ê°€ëŠ¥"));

		IInteractable::Execute_Interact(FocusedActor, this);

		UE_LOG(LogTemp, Warning, TEXT("âœ… Execute_Interact í˜¸ì¶œ ì™„ë£Œ"));
	}

	if (!FocusedActor) return;

	if (TryPickupFuel(FocusedActor))
	{
		return;
	}
	if (TryToggleFuelPosition(FocusedActor)) return;
	if (TryDropFuel(FocusedActor)) return;

	// ê¸°íƒ€ ì¸í„°ë™ì…˜
	if (FocusedActor->Implements<UInteractable>())
	{
		IInteractable::Execute_Interact(FocusedActor, this);
	}
}


// íŠ¸ë¦¬ê±°ê°€ ì˜¤ë²„ë© ì‹œì‘í•  ë•Œ í˜¸ì¶œ
void APlayerCharacter::OnInteractionTriggerBeginOverlap(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor,
														 UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult)
{
	if (OtherActor && OtherActor->Implements<UInteractable>())
	{
		// ìƒí˜¸ì‘ìš© ê°€ëŠ¥í•œ ì˜¤ë¸Œì íŠ¸ì´ë©´ FocusedActorë¡œ ì„¤ì •
		FocusedActor = OtherActor;
	}
}

// íŠ¸ë¦¬ê±°ê°€ ì˜¤ë²„ë© ì¢…ë£Œí•  ë•Œ í˜¸ì¶œ
void APlayerCharacter::OnInteractionTriggerEndOverlap(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor,
													   UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
	if (OtherActor == FocusedActor)
	{
		// ì˜¤ë²„ë©ì´ ëë‚˜ë©´ FocusedActor ì´ˆê¸°í™”
		FocusedActor = nullptr;
	}
}

void APlayerCharacter::EnterLadderMode(ALadderActor* Ladder)
{
	if (bIsOnLadder || !Ladder) return;

	bIsOnLadder = true;
	CurrentLadder = Ladder;
	
	bIsClimbingOffLadderTop = false;

	// ì¤‘ë ¥ ì œê±° + ì´ë™ ëª¨ë“œ ë³€ê²½
	auto* Movement = GetCharacterMovement();
	Movement->SetMovementMode(MOVE_Flying);
	Movement->GravityScale = 0.f;

	// ğŸ”¥ ê´€ì„± ì œê±°ìš© ì„¤ì •
	Movement->BrakingDecelerationFlying = 4096.f; // ì•„ì£¼ ë¹ ë¥´ê²Œ ë©ˆì¶”ë„ë¡ ì„¤ì •
	Movement->BrakingFrictionFactor = 10.0f;      // ë§ˆì°°ê³„ìˆ˜ ì¦ê°€
	Movement->BrakingFriction = 2048.f; 

	UE_LOG(LogTemp, Warning, TEXT("â–¶ ì‚¬ë‹¤ë¦¬ íƒ‘ìŠ¹"));
}

void APlayerCharacter::ExitLadderMode()
{
	if (!bIsOnLadder) return;

	bIsOnLadder = false;
	CurrentLadder = nullptr;

	auto* Movement = GetCharacterMovement();
	Movement->SetMovementMode(MOVE_Walking);
	Movement->GravityScale = 1.f;

	// í•„ìš” ì‹œ ë³µì›
	Movement->BrakingDecelerationFlying = 0.f;
	Movement->BrakingFrictionFactor = 1.0f;
	Movement->BrakingFriction = 0.f;

	UE_LOG(LogTemp, Warning, TEXT("â–¼ ì‚¬ë‹¤ë¦¬ í•˜ì°¨"));
}
void APlayerCharacter::OnActionMoveUpDown(const FInputActionValue& Value)
{
	if (!bIsOnLadder || bIsClimbingOffLadderTop || bIsExitingLadderTopForward)
		return;

	float Input = Value.Get<float>();
	float SpeedScale = 0.3f;

	// âœ… ì‚¬ë‹¤ë¦¬ ê¼­ëŒ€ê¸° ë„ë‹¬: ì½œë¦¬ì „ ì¤‘ì‹¬ì´ TopZë³´ë‹¤ ë†’ì•„ì¡Œì„ ë•Œ
	if (CurrentLadder && Input > 0.f && !bIsClimbingOffLadderTop)
	{
		float PlayerCenterZ = GetActorLocation().Z; // ì½œë¦¬ì „ ì¤‘ì‹¬

		if (PlayerCenterZ >= CurrentLadder->TopZ)
		{
			bIsClimbingOffLadderTop = true;
			return;
		}
	}

	// âœ… ì‚¬ë‹¤ë¦¬ ì•„ë˜ íƒˆì¶œ
	if (Input < 0.f)
	{
		float PlayerBottomZ = GetActorLocation().Z - GetCapsuleComponent()->GetScaledCapsuleHalfHeight();
		if (PlayerBottomZ <= CurrentLadder->BottomZ)
		{
			ExitLadderMode();
			return;
		}
	}

	// âœ… ì¼ë°˜ ì´ë™
	if (FMath::IsNearlyZero(Input))
	{
		GetCharacterMovement()->StopMovementImmediately();
		GetCharacterMovement()->Velocity = FVector::ZeroVector;
		return;
	}

	AddMovementInput(FVector::UpVector, Input * SpeedScale);
}

void APlayerCharacter::NotifyHit(
	UPrimitiveComponent* MyComp,
	AActor* Other,
	UPrimitiveComponent* OtherComp,
	bool bSelfMoved,
	FVector HitLocation,
	FVector HitNormal,
	FVector NormalImpulse,
	const FHitResult& Hit)
{
	Super::NotifyHit(MyComp, Other, OtherComp, bSelfMoved, HitLocation, HitNormal, NormalImpulse, Hit);

	if (OtherComp)
	{
		UE_LOG(LogTemp, Warning, TEXT("ğŸ’¥ ì¶©ëŒí•œ ì»´í¬ë„ŒíŠ¸ ì´ë¦„: %s (ì†Œì† ì•¡í„°: %s)"),
			*OtherComp->GetName(),
			*Other->GetName());
	}
}


bool APlayerCharacter::TryPickupFuel(AActor* Target)
{
	UE_LOG(LogTemp, Warning, TEXT("ì—°ë£Œê°€ ì—†ëŠ” ìƒíƒœì—ì„œ ìƒí˜¸ì‘ìš© ì…ë ¥1"));

	if (!CarriedFuel && Target->IsA<AFuelActor>())
	{
		UE_LOG(LogTemp, Warning, TEXT("ì—°ë£Œê°€ ì—†ëŠ” ìƒíƒœì—ì„œ ìƒí˜¸ì‘ìš© ì…ë ¥2"));

		CarriedFuel = Cast<AFuelActor>(Target);
		if (CarriedFuel)
		{
			UE_LOG(LogTemp, Warning, TEXT("ì—°ë£Œê°€ ì—†ëŠ” ìƒíƒœì—ì„œ ìƒí˜¸ì‘ìš© ì…ë ¥3"));

			CarriedFuel->AttachTo(GetMesh(), TEXT("CarrySocketFront"));
			bIsFuelInBackPosition = false;
			return true;
		}
	}
	return false;
}

bool APlayerCharacter::TryToggleFuelPosition(AActor* Target)
{
	UE_LOG(LogTemp, Warning, TEXT("ì—°ë£Œë“  ìƒíƒœì—ì„œ ìƒí˜¸ì‘ìš© ì…ë ¥5"));

	if (CarriedFuel && Target != CarriedFuel)
	{
		UE_LOG(LogTemp, Warning, TEXT("ì—°ë£Œë¥¼ ë“  ìƒíƒœì—ì„œ ìƒí˜¸ì‘ìš© ì…ë ¥6"));

		FName NewSocket = bIsFuelInBackPosition ? TEXT("CarrySocketFront") : TEXT("CarrySocketBack");
		CarriedFuel->AttachTo(GetMesh(), NewSocket);
		bIsFuelInBackPosition = !bIsFuelInBackPosition;
		return true;
	}
	return false;
}


bool APlayerCharacter::TryDropFuel(AActor* Target)
{
	UE_LOG(LogTemp, Warning, TEXT("ì—°ë£Œë¥¼ ë“  ìƒíƒœì—ì„œ ì—°ë£Œ ë‚´ë ¤ë†“ê¸°"));

	if (CarriedFuel && Target == CarriedFuel)
	{
		CarriedFuel->DetachFrom();
		CarriedFuel = nullptr;
		bIsFuelInBackPosition = false;
		return true;
	}
	return false;
}

void APlayerCharacter::SetSeeThroughEffect()
{
	UE_LOG(LogTemp, Warning, TEXT("í…ŒìŠ¤íŠ¸1"));

	static const FName ParamName(TEXT("Distance"));
	if (!SomeMPCAsset) return;
	
	UE_LOG(LogTemp, Warning, TEXT("í…ŒìŠ¤íŠ¸2"));

	UMaterialParameterCollectionInstance* MPCInstance = GetWorld()->GetParameterCollectionInstance(SomeMPCAsset);
	if (MPCInstance)
	{	UE_LOG(LogTemp, Warning, TEXT("í…ŒìŠ¤íŠ¸3"));

		MPCInstance->SetScalarParameterValue(ParamName, bCheckInternal ? 1800.f : 0.f); // 500ì€ ê¸°ì¡´ ì‚¬ìš©ëœ ê±°ë¦¬
	}
}